import type { INodeProperties } from 'n8n-workflow';

export const deviceOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['device'] } },
		options: [
			{ name: 'Approve/Reject', value: 'approval', action: 'Approve or reject devices' },
			{ name: 'Cancel Maintenance', value: 'cancelMaintenance', action: 'Cancel maintenance window' },
			{ name: 'Delete', value: 'delete', action: 'Delete a device' },
			{ name: 'Get', value: 'get', action: 'Get a device' },
			{ name: 'Get Activities', value: 'getActivities', action: 'Get device activities' },
			{ name: 'Get Alerts', value: 'getAlerts', action: 'Get device alerts' },
			{ name: 'Get Custom Fields', value: 'getCustomFields', action: 'Get device custom fields' },
			{ name: 'Get Dashboard URL', value: 'getDashboardUrl', action: 'Get device dashboard URL' },
			{ name: 'Get Disks', value: 'getDisks', action: 'Get device disks' },
			{ name: 'Get Jobs', value: 'getJobs', action: 'Get active jobs' },
			{ name: 'Get Last Logged On User', value: 'getLastUser', action: 'Get last logged on user' },
			{ name: 'Get Many', value: 'getAll', action: 'Get many devices' },
			{ name: 'Get OS Patch Installs', value: 'getOsPatchInstalls', action: 'Get OS patch install history' },
			{ name: 'Get OS Patches', value: 'getOsPatches', action: 'Get device OS patches' },
			{ name: 'Get Policy Overrides', value: 'getPolicyOverrides', action: 'Get policy overrides' },
			{ name: 'Get Processors', value: 'getProcessors', action: 'Get device processors' },
			{ name: 'Get Software', value: 'getSoftware', action: 'Get device software' },
			{ name: 'Get Software Patch Installs', value: 'getSoftwarePatchInstalls', action: 'Get software patch install history' },
			{ name: 'Get Software Patches', value: 'getSoftwarePatches', action: 'Get software patches' },
			{ name: 'Get Scripting Options', value: 'getScriptingOptions', action: 'Get device scripting options' },
			{ name: 'Get Volumes', value: 'getVolumes', action: 'Get device volumes' },
			{ name: 'Reboot', value: 'reboot', action: 'Reboot a device' },
			{ name: 'Reset Policy Overrides', value: 'resetPolicyOverrides', action: 'Reset policy overrides' },
			{ name: 'Run Script', value: 'runScript', action: 'Run a script on device' },
			{ name: 'Schedule Maintenance', value: 'scheduleMaintenance', action: 'Schedule maintenance window' },
			{ name: 'Update', value: 'update', action: 'Update a device' },
			{ name: 'Update Custom Fields', value: 'updateCustomFields', action: 'Update device custom fields' },
		],
		default: 'getAll',
	},
];

export const deviceFields: INodeProperties[] = [
	{
		displayName: 'Organization',
		name: 'deviceOrgId',
		type: 'resourceLocator',
		default: { mode: 'list', value: '' },
		displayOptions: { show: { resource: ['device'], operation: ['getAll'] } },
		modes: [
			{
				displayName: 'From List',
				name: 'list',
				type: 'list',
				typeOptions: { searchListMethod: 'searchOrganizations', searchable: true },
			},
			{
				displayName: 'By ID',
				name: 'id',
				type: 'string',
				placeholder: 'e.g., 1 or {{ $json.orgId }}',
			},
		],
		description: 'Filter devices by organization (optional). Supports expressions.',
	},
	{
		displayName: 'Device',
		name: 'deviceId',
		type: 'resourceLocator',
		default: { mode: 'list', value: '' },
		required: true,
		displayOptions: {
			show: {
				resource: ['device'],
				operation: [
					'get', 'update', 'delete', 'getActivities', 'getAlerts', 'getSoftware',
					'getDisks', 'getVolumes', 'getOsPatches', 'getOsPatchInstalls',
					'getSoftwarePatches', 'getSoftwarePatchInstalls', 'getCustomFields',
					'updateCustomFields', 'reboot', 'runScript', 'getProcessors', 'getJobs',
					'getLastUser', 'getDashboardUrl', 'getPolicyOverrides', 'resetPolicyOverrides',
					'scheduleMaintenance', 'cancelMaintenance', 'getScriptingOptions',
				],
			},
		},
		modes: [
			{
				displayName: 'From List',
				name: 'list',
				type: 'list',
				typeOptions: { searchListMethod: 'searchDevices', searchable: true },
			},
			{
				displayName: 'By ID',
				name: 'id',
				type: 'string',
				placeholder: 'e.g., 1 or {{ $json.deviceId }}',
			},
		],
		description: 'The device to operate on. Supports expressions.',
	},
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		default: false,
		displayOptions: {
			show: {
				resource: ['device'],
				operation: ['getAll', 'getActivities', 'getAlerts', 'getSoftware', 'getOsPatches', 'getOsPatchInstalls', 'getSoftwarePatches', 'getSoftwarePatchInstalls', 'getJobs'],
			},
		},
		description: 'Whether to return all results or only up to a given limit',
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		default: 50,
		displayOptions: {
			show: {
				resource: ['device'],
				operation: ['getAll', 'getActivities', 'getAlerts', 'getSoftware', 'getOsPatches', 'getOsPatchInstalls', 'getSoftwarePatches', 'getSoftwarePatchInstalls', 'getJobs'],
				returnAll: [false],
			},
		},
		typeOptions: { minValue: 1, maxValue: 1000 },
		description: 'Max number of results to return',
	},
	{
		displayName: 'Reboot Mode',
		name: 'rebootMode',
		type: 'options',
		default: 'NORMAL',
		required: true,
		displayOptions: { show: { resource: ['device'], operation: ['reboot'] } },
		options: [
			{ name: 'Normal', value: 'NORMAL' },
			{ name: 'Forced', value: 'FORCED' },
		],
		description: 'Type of reboot to perform',
	},
	{
		displayName: 'Script Language',
		name: 'scriptingLanguage',
		type: 'options',
		default: '',
		displayOptions: { show: { resource: ['device'], operation: ['getScriptingOptions'] } },
		options: [
			{ name: 'All', value: '' },
			{ name: 'PowerShell', value: 'powershell' },
			{ name: 'Batch', value: 'batch' },
			{ name: 'Bash', value: 'bash' },
			{ name: 'Python', value: 'python' },
		],
		description: 'Filter scripting options by language',
	},
	{
		displayName: 'Script',
		name: 'scriptId',
		type: 'resourceLocator',
		default: { mode: 'list', value: '' },
		required: true,
		displayOptions: { show: { resource: ['device'], operation: ['runScript'] } },
		modes: [
			{
				displayName: 'From List',
				name: 'list',
				type: 'list',
				typeOptions: { searchListMethod: 'searchScripts', searchable: true },
			},
			{
				displayName: 'By ID',
				name: 'id',
				type: 'string',
				placeholder: 'e.g., 1 or {{ $json.scriptId }}',
			},
		],
		description: 'The script to run. Supports expressions.',
	},
	{
		displayName: 'Script Parameters',
		name: 'scriptParameters',
		type: 'string',
		default: '',
		placeholder: 'e.g., param1=value1 or {{ $json.params }}',
		displayOptions: { show: { resource: ['device'], operation: ['runScript'] } },
		description: 'Parameters to pass to the script. Supports expressions for dynamic values.',
	},
	{
		displayName: 'Run As (Credential)',
		name: 'runAs',
		type: 'string',
		default: '',
		placeholder: 'e.g., system, sysop, or 66',
		displayOptions: { show: { resource: ['device'], operation: ['runScript'] } },
		description:
			'The credential or role to use when running the script. Use "system" (lowercase), credential name (e.g., sysop), or credential ID (e.g., 66). Defaults to "system" if empty.',
	},
	{
		displayName: 'Custom Fields',
		name: 'customFields',
		type: 'fixedCollection',
		typeOptions: { multipleValues: true },
		default: {},
		displayOptions: { show: { resource: ['device'], operation: ['updateCustomFields'] } },
		options: [
			{
				displayName: 'Field',
				name: 'field',
				values: [
					{
						displayName: 'Field Name',
						name: 'name',
						type: 'resourceLocator',
						default: { mode: 'list', value: '' },
						modes: [
							{
								displayName: 'From List',
								name: 'list',
								type: 'list',
								typeOptions: { searchListMethod: 'searchCustomFields', searchable: true },
							},
							{ displayName: 'By Name', name: 'id', type: 'string', placeholder: 'myCustomField' },
						],
						description: 'Name of the custom field',
					},
					{
						displayName: 'Value',
						name: 'value',
						type: 'string',
						default: '',
						placeholder: 'e.g., myValue or {{ $json.fieldValue }}',
						description: 'Value for the custom field. Supports expressions.',
					},
				],
			},
		],
		description: 'Custom fields to update',
	},
	{
		displayName: 'Update Fields',
		name: 'updateFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['device'], operation: ['update'] } },
		options: [
			{
				displayName: 'Display Name',
				name: 'displayName',
				type: 'string',
				default: '',
				placeholder: 'e.g., Server-01 or {{ $json.hostname }}',
				description: 'Display name for the device. Supports expressions.',
			},
			{
				displayName: 'Location',
				name: 'locationId',
				type: 'resourceLocator',
				default: { mode: 'list', value: '' },
				modes: [
					{
						displayName: 'From List',
						name: 'list',
						type: 'list',
						typeOptions: { searchListMethod: 'searchLocations', searchable: true },
					},
					{ displayName: 'By ID', name: 'id', type: 'string' },
				],
				description: 'Location to assign the device to',
			},
		],
	},
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Filter',
		default: {},
		displayOptions: { show: { resource: ['device'], operation: ['getAll'] } },
		options: [
			{
				displayName: 'Device Filter',
				name: 'df',
				type: 'string',
				default: '',
				placeholder: 'e.g., status=APPROVED or {{ $json.filter }}',
				description: 'Device filter query string. Supports expressions for dynamic filtering.',
			},
		],
	},
	{
		displayName: 'Approval Mode',
		name: 'approvalMode',
		type: 'options',
		default: 'APPROVE',
		required: true,
		displayOptions: { show: { resource: ['device'], operation: ['approval'] } },
		options: [
			{ name: 'Approve', value: 'APPROVE' },
			{ name: 'Reject', value: 'REJECT' },
		],
		description: 'Whether to approve or reject the devices',
	},
	{
		displayName: 'Device IDs',
		name: 'approvalDeviceIds',
		type: 'string',
		default: '',
		required: true,
		placeholder: 'e.g., 1,2,3 or {{ $json.deviceIds }}',
		displayOptions: { show: { resource: ['device'], operation: ['approval'] } },
		description: 'Comma-separated list of device IDs to approve/reject. Supports expressions like {{ $json.devices.map(d => d.id).join(",") }}.',
	},
	{
		displayName: 'Maintenance Start',
		name: 'maintenanceStart',
		type: 'dateTime',
		default: '',
		required: true,
		displayOptions: { show: { resource: ['device'], operation: ['scheduleMaintenance'] } },
		description: 'When the maintenance window starts',
	},
	{
		displayName: 'Maintenance End',
		name: 'maintenanceEnd',
		type: 'dateTime',
		default: '',
		required: true,
		displayOptions: { show: { resource: ['device'], operation: ['scheduleMaintenance'] } },
		description: 'When the maintenance window ends',
	},
	{
		displayName: 'Disable Alerts',
		name: 'maintenanceDisableAlerts',
		type: 'boolean',
		default: true,
		displayOptions: { show: { resource: ['device'], operation: ['scheduleMaintenance'] } },
		description: 'Whether to disable alerts during maintenance',
	},
];
